spring.datasource.url=jdbc:postgresql://root:LmuzCUg59hmzKPZOhWgP0DQEzM71HiTA@dpg-d4no8c0gjchc73c00iag-a/inventario_tienda_k2qb
spring.datasource.username=root
spring.datasource.password=LmuzCUg59hmzKPZOhWgP0DQEzM71HiTA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto del servidor
server.port=8080

# Aplicacion
spring.application.name=inventario-backend